# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='abr_bilhete',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='horario',
            name='status',
            field=models.CharField(choices=[('andamento', 'em andamento'), ('parado', 'parado'), ('concluido', 'concluido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='horario',
            name='tipo_atendimento',
            field=models.CharField(choices=[('', ''), (' ', ' ')], max_length=50),
        ),
    ]
