# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abr_bilhete', models.DateTimeField()),
                ('fecha_bilhete', models.DateTimeField()),
                ('tipo_atendimento', models.CharField(choices=[('', ''), (' ', ' ')], max_length=1)),
                ('dias_fechamento', models.IntegerField()),
                ('horas_fechamento', models.TimeField()),
                ('encer_bilhete', models.DateField()),
                ('dias_encer', models.IntegerField()),
                ('status', models.CharField(choices=[('andamento', 'em andamento'), ('parado', 'parado'), ('concluido', 'concluido')], max_length=1)),
                ('pendencia', models.TextField()),
            ],
        ),
    ]
