# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170601_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='abr_bilhete',
            new_name='abertura_do_bilhete',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='dias_encer',
            new_name='dias_de_encerramento',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='encer_bilhete',
            new_name='encerramento_do_bilhete',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='fecha_bilhete',
            new_name='fechamento_do_bilhete',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='tipo_atendimento',
            new_name='tipo_de_atendimento',
        ),
    ]
