# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170601_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='status',
            field=models.CharField(choices=[('trecho com redundancia fisica', 'trecho sem redundancia fisica'), ('trecho com atendimento critico', 'parado')], max_length=50),
        ),
    ]
