# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170622_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='cabo',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='cidade',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='derivacao_de_ocorrencia',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='endereco',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='mais_informacoes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='manutencao',
            field=models.CharField(choices=[(' ', 'Corretiva'), (' ', 'Preventiva'), (' ', 'Programada')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='maps',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='responsavel_pelo_rompimento',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='resumo_da_ocorrencia',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='tipo_de_ocorrencia',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='trecho',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
