# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170705_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='objeto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
