# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocoloEmp', models.CharField(max_length=60, null=True)),
                ('atendenteEmp', models.CharField(max_length=60, null=True)),
                ('causaOcorrencia', models.TextField(default='--')),
                ('tipoManutencao', models.CharField(max_length=60, null=True, verbose_name='Tipo de ocorrencia')),
            ],
        ),
        migrations.CreateModel(
            name='bilhete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura_do_bilhete', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechamento_do_bilhete', models.DateTimeField(null=True)),
                ('tipo_de_atendimento', models.CharField(choices=[('TSRF', 'Trecho sem redundancia fisica'), ('TCRF', 'Trecho com redundancia fisica'), ('TCAT', 'Trecho com atendimento critico')], max_length=50, null=True)),
                ('slaDias_fechamento', models.IntegerField(null=True)),
                ('slaHoras_fechamento', models.TimeField(null=True)),
                ('slaEncerramento', models.DateField(null=True, verbose_name='encerramento')),
                ('slaDias_de_encerramento', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Fechado', 'Fechado'), ('Finalizado', 'Finalizado')], max_length=50, null=True)),
                ('pendencia', models.TextField(default='----')),
                ('flagModerador', models.TextField(default='----')),
                ('msgModerador', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='informacao_servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutencao', models.CharField(choices=[('corretiva', 'Corretiva'), ('Preventiva', 'Preventiva'), ('Programada', 'Programada')], max_length=50, null=True)),
                ('derivacao_de_ocorrencia', models.CharField(max_length=60, null=True)),
                ('responsavel_pelo_rompimento', models.CharField(max_length=60, null=True)),
                ('cabo', models.CharField(max_length=60, null=True)),
                ('resumo_da_ocorrencia', models.CharField(max_length=60, null=True)),
                ('mais_informacoes', models.TextField(null=True)),
                ('equipeLancamento', models.CharField(max_length=60, null=True)),
                ('equipeFusao', models.CharField(max_length=60, null=True)),
                ('tecnicoMedicao', models.CharField(max_length=60, null=True)),
                ('supervisor', models.CharField(max_length=60, null=True)),
                ('tempo', models.CharField(choices=[('aberto', 'Aberto'), ('chuvoso', 'Chuvoso'), ('nublado', 'Nublado')], max_length=50, null=True, verbose_name='Tempo')),
                ('postesEnv', models.CharField(max_length=60, null=True)),
                ('data_de_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(null=True)),
                ('tempo_decorrido', models.TimeField(null=True)),
                ('resumo_do_servico', models.TextField(null=True)),
                ('id_bilhete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=60, null=True)),
                ('cidade', models.CharField(max_length=60, null=True)),
                ('trecho', models.CharField(max_length=60, null=True)),
                ('localizacao', models.CharField(max_length=60, null=True)),
                ('pontoA', models.IntegerField()),
                ('pontoB', models.IntegerField()),
                ('id_bilhete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetos', models.CharField(choices=[(' ', 'Cabo'), (' ', 'Caixa de emenda')], max_length=50, null=True)),
                ('fabricante', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('bandejas', models.IntegerField(null=True)),
                ('fibras', models.IntegerField(null=True)),
                ('derivacoes', models.IntegerField(null=True)),
                ('poste', models.CharField(max_length=50, null=True)),
                ('id_bilhete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='material_retorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_retorno', models.CharField(max_length=15, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('id_bilhete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='parecer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_campo', models.CharField(max_length=60, null=True, verbose_name='fiscal de campo')),
                ('parecer_campo', models.CharField(max_length=60, null=True, verbose_name='parecer de campo')),
                ('fiscal_administrativo', models.CharField(max_length=60, null=True, verbose_name='fiscal administrativo')),
                ('parecer_adm', models.CharField(max_length=60, null=True, verbose_name='parecer administrativo')),
                ('id_bilhete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='id_bilhete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete'),
        ),
    ]
