# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bilhete',
            fields=[
                ('abertura_do_bilhete', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechamento_do_bilhete', models.DateTimeField(null=True)),
                ('tipo_de_atendimento', models.CharField(choices=[(' ', 'Trecho sem redundancia fisica'), (' ', 'Trecho com redundancia fisica'), (' ', 'Trecho com atendimento critico')], max_length=50, null=True)),
                ('dias_fechamento', models.IntegerField(null=True)),
                ('horas_fechamento', models.TimeField(null=True)),
                ('encerramento_do_bilhete', models.DateField(null=True, verbose_name='encerramento')),
                ('dias_de_encerramento', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[(' ', 'Pendente'), (' ', 'Fechado'), (' ', 'Finalizado')], max_length=50, null=True)),
                ('pendencia', models.TextField(default='----')),
                ('numero_do_bilhete', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='informacoes_de_ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_ocorrencia', models.CharField(max_length=60, null=True)),
                ('manutencao', models.CharField(choices=[(' ', 'Corretiva'), (' ', 'Preventiva'), (' ', 'Programada')], max_length=50, null=True)),
                ('derivacao_de_ocorrencia', models.CharField(max_length=60, null=True)),
                ('responsavel_pelo_rompimento', models.CharField(max_length=60, null=True)),
                ('cabo', models.CharField(max_length=60, null=True)),
                ('resumo_da_ocorrencia', models.CharField(max_length=60, null=True)),
                ('mais_informacoes', models.TextField(null=True)),
                ('id_bilhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='locais_de_ocorrencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=60, null=True)),
                ('cidade', models.CharField(max_length=60, null=True)),
                ('trecho', models.CharField(max_length=60, null=True)),
                ('maps', models.CharField(max_length=60, null=True)),
                ('id_bilhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetos', models.CharField(choices=[(' ', 'Cabo'), (' ', 'Caixa de emenda')], max_length=50, null=True)),
                ('fabricante', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('bandejas', models.IntegerField(null=True)),
                ('fibras', models.IntegerField(null=True)),
                ('derivacoes', models.IntegerField(null=True)),
                ('poste', models.CharField(max_length=50, null=True)),
                ('id_bilhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='material_retorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_retorno', models.CharField(max_length=15, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('id_bilhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='ocorrencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_interjato', models.CharField(max_length=60, null=True)),
                ('atendente_interjato', models.CharField(max_length=50, null=True)),
                ('id_bilhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='parecer_pop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_campo', models.CharField(max_length=60, null=True, verbose_name='fiscal de campo')),
                ('parecer_campo', models.CharField(max_length=60, null=True, verbose_name='parecer de campo')),
                ('fiscal_administrativo', models.CharField(max_length=60, null=True, verbose_name='fiscal administrativo')),
                ('parecer_adm', models.CharField(max_length=60, null=True, verbose_name='parecer administrativo')),
                ('id_bilhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
        migrations.CreateModel(
            name='servico_interjato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe_de_lancamento', models.CharField(max_length=60, null=True)),
                ('equipe_de_fusao', models.CharField(max_length=60, null=True)),
                ('tecnico_de_medicao', models.CharField(max_length=60, null=True)),
                ('supervisor', models.CharField(max_length=60, null=True)),
                ('tempo', models.CharField(choices=[(' ', 'Aberto'), (' ', 'Chuvoso'), (' ', 'Nublado')], max_length=50, null=True)),
                ('postes_envolvidos', models.CharField(max_length=60, null=True)),
                ('data_de_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(null=True)),
                ('tempo_decorrido', models.TimeField(null=True)),
                ('resumo_do_servico', models.TextField(null=True)),
                ('id_bilhete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bilhete')),
            ],
        ),
    ]
