# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilhete',
            name='numero_do_bilhete',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='numero do bilhete'),
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Fechado', 'Fechado'), ('Finalizado', 'Finalizado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='tipo_de_atendimento',
            field=models.CharField(choices=[('TSRF', 'Trecho sem redundancia fisica'), ('TCRF', 'Trecho com redundancia fisica'), ('TCAT', 'Trecho com atendimento critico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informacoes_de_ocorrencia',
            name='manutencao',
            field=models.CharField(choices=[('corretiva', 'Corretiva'), ('Preventiva', 'Preventiva'), ('Programada', 'Programada')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servico_interjato',
            name='tempo',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('chuvoso', 'Chuvoso'), ('nublado', 'Nublado')], max_length=50, null=True),
        ),
    ]
