# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170914_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencias',
            name='id',
        ),
        migrations.AlterField(
            model_name='ocorrencias',
            name='id_bilhete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.bilhete'),
        ),
    ]
